### ISSUE TITLE
"Reference to type 'IHttpSettingsContainer' claims it is defined in 'Flurl.Http', but it could not be found" with Flurl.Http 4.0.

### ISSUE THREAD

**Issue by chriswill** [cajuncoding/FlurlGraphQL#4]
I'm wondering if you've seen this error working with Flurl.Http 4.0 "Reference to type 'IHttpSettingsContainer' claims it is defined in 'Flurl.Http', but it could not be found".

I saw it with a project where I've been using FlurlGraphQL.  Other Flurl.Http projects were not reporting this issue.

**Comment by cajuncoding** [comment]
This is the first report of the error, but I am not at all surprised.

Since Flurl 4.0 is brand new FlurlGraphQL has not been updated to support it yet as there are many breaking changes….not the least of which is a major change to the JSON parser which now uses `System.Text.Json` so the GraphQL response parser has to be rewritten to be compliant.

Even with the use of the `Flurl.Http.Newtonsoft` compatibility package there are certainly underlying breaking changes that impact FlurlGraphQL.

I will try to update it as this is better way forward but I’m not exactly sure when I will have time, but hopefully early in 2024.

I had time 6 months ago and was waiting on Flurl 4.0 to be released but it took very a long time to be finalized.

Thanks for using FlurlGraphQL! If you haven’t yet give it a Star in GitHub, and I’ll try to get it updated for v4.0 soon!

**Comment by cajuncoding** [comment]
But I will try to resolve any issues using the new compatibility package `Flurl.Http.Newtonsoft` first which should be relatively straightforward.

Then look into full 4.0 compatibility as a new version release.

**Comment by chriswill** [comment]
Hi, thanks for the response... just wanted to report it and get it on your roadmap.  I know how hard it is to keep an open source project moving forward, so I appreciate all you do.  Thanks!

**Comment by cajuncoding** [comment]
Quick update…I’m actively working on Flurl 4.0 support now. 

I’ve already re-worked the entire GraphQL pipeline to now fully abstract all JSON processing which enables support for multiple types of serialization (e.g. Newtonsoft.Json & System.Text.Json).

Am now working on the (new) System.Text.Json parsing logic… 

I hope to have a preview release soon in the next week or so.

**Comment by cajuncoding** [comment]
Ok, I've released the new FlurlGraphQL v2.0 with full System.Text.Json support and compatibility with Flurl v4.0+....

Readme Docs have been updated with breaking changes and improvements. And new library has been published to NuGet: 
https://www.nuget.org/packages/FlurlGraphQL/
