### ISSUE TITLE
Fragments not supported? Error code 400?

### ISSUE THREAD

**Issue by jeffward01** [cajuncoding/FlurlGraphQL#5]
Hello,

I am having some issues with my queries contain fragments.  Here is an example:

Url:
```text
 https://api.runpod.io/graphql
```

Documentation for[ GraphQL (RunPod)](https://graphql-spec.runpod.io/#query-gpuTypes):
 

Query:

```graphql
query gpuTypes($input: GpuTypeFilter) {
  gpuTypes(input: $input) {
    lowestPrice {
      ...LowestPriceFragment
    }
    maxGpuCount
    id
    displayName
    manufacturer
    memoryInGb
    cudaCores
    secureCloud
    communityCloud
    securePrice
    communityPrice
    oneMonthPrice
    threeMonthPrice
    oneWeekPrice
    communitySpotPrice
    secureSpotPrice
  }
}
````

My code:
````csharp

    public async Task<ICollection<GpuType>> GetAllGpuTypesAsync(CancellationToken cancellationToken = default)
    {
        var gpuTypeFilter = new GpuTypeFilter { Id = "", Ids = Array.Empty<string>() };
        IGraphQLQueryResults<GpuType>? results = await _runPodGraphQLUrlService.GetGraphQLUrl()
            .WithGraphQLQuery(GetAllGpuTypesQuery.Query)
           .SetGraphQLVariable("input",gpuTypeFilter)
            .PostGraphQLQueryAsync(cancellationToken)
            .ReceiveGraphQLQueryResults<GpuType>();
        return results.ToList();
    }


````

Response:

>[400-BadRequest] The GraphQL server returned an error response for the query. This is likely caused by a malformed/non-parsable query, or a Schema validation issue; please validate the query syntax, operation name, and arguments to ensure that the query is valid. Something went wrong. Please try again later or contact support [At=1,16]. Something went wrong. Please try again later or contact support [At=1,16]. Call failed with status code 400 (Bad Request)

When my queries do not contain fragments, I have no issue with queries.

Am I doing something wrong?

**Comment by cajuncoding** [comment]
This is not an issue with `FlurlGraphQL` at all... the error message is accurate with the GraphQL server you are using (e.g. `RunPod`) returning a `400-Bad Request` and this is valid. 

You are not defining your `fragment`  in your query....  I'll refer you over to the official GraphQL docs and examples on using Fragments at graphql.io: https://graphql.org/learn/queries/#fragments

You must define the _fragment_ in the query body -- otherwise it doesn't know what fields to replace your Fragment with? 🤷‍♂️... That's a bad request.  

I also quickly looked at the docs you linked and I'm not sure why their docs leave out the _fragments_ but also use them throughout their examples.... but those are all mal-formed GraphQL queries in their current state on their page if you just copy/paste them (they are missing the definition of those _fragments_)....

I don't have an API Key to query `RunPod` but I have my own `Star Wars` test server using `HotChocolate` and `Fragments` work without issue...  🚀

To help you out a little more I went ahead and added a new Unit Test case to explicitly validate there are no issues with the use of Fragments here: https://github.com/cajuncoding/FlurlGraphQL/blob/4d6eda0986e9e89e1fa02a98363cb2dbc59e6bfa/FlurlGraphQL.Tests/FlurlGraphQLQueryingSimplePostTests.cs#L54-L71

The other reason this is not an issue for FlurlGraphQL is because this is all server-side behaviour.... FlurlGraphQL is primarily concerned with parsing the response Json; generating the original request is simply part of the defined spec. In the response _fragments_ don't exist, only the Schema based Response Type (response data model). So as long as that data model can be (even partially) mapped into your `GpuType` class then it will parse as much as it can.

**Comment by cajuncoding** [comment]
@jeffward01 also thank you for using FlurlGraphQL! 

If you found it helpful, the easiest way for you to help is to give it a GitHub Star ⭐! It's completely free and will help the project out!
